# Google Sheets connection
[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1nhPXyRkC6kjMMC7XSHz11zq3EEw2FgdSAhfKbnmOXw4/edit?usp=sharing"
worksheet = "Sheet1"
type = "service_account"
project_id = "your-project-id"
private_key_id = "your-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_HERE\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account@your-project.iam.gserviceaccount.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"